---
# This playbook will install nginx

- name: update apt
  apt: update_cache=yes

- name: install git wget curl vim
  apt: pkg={{item}} install_recommends=no state=installed
  with_items:
    - git
    - wget
    - curl
    - perl
    - vim

- name: add apt repository key
  apt_key:
    url: "http://nginx.org/keys/nginx_signing.key"

- name: add apt repository
  apt_repository:
    repo: "deb http://nginx.org/packages/mainline/ubuntu/ trusty nginx"

- name: install nginx
  apt: 
    name: "nginx=1.9.0*"
    state: present
    update_cache: yes
- name: make directories
  shell: mkdir -p {{item}}
  with_items:
    - /var/www/html
    - /var/cache/html
    - /etc/nginx/certs
    - /etc/nginx/sites-enabled
- name: copy nginx config file
  template: src=default.conf.j2 dest=/default.conf mode=0777

- name: copy default html page
  template: src=index.html dest=/index.html mode=0777

- name: create morpheus entrypoint
  template: src=morpheus-entrypoint.sh.j2 dest=/entrypoint.sh mode=0777

- name: stop nginx
  shell: service nginx stop && update-rc.d -f nginx remove
  ignore_errors: yes
